# Generated by Django 5.0.1 on 2024-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=9)),
                ('address', models.TextField(max_length=200)),
                ('istitute', models.CharField(max_length=30)),
                ('graduation_date', models.DateField()),
                ('workplace', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('skill_name', models.CharField(max_length=20)),
                ('skill_detail', models.TextField(max_length=200)),
            ],
        ),
    ]
