# Generated by Django 5.0.1 on 2024-02-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_education_skils_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcv',
            name='graduation_date',
        ),
        migrations.RemoveField(
            model_name='personalcv',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='personalcv',
            name='skill_detail',
        ),
        migrations.RemoveField(
            model_name='personalcv',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='personalcv',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='personalcv',
            name='workplace',
        ),
    ]
