# Generated by Django 5.0.1 on 2024-02-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_personalcv_graduation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcv',
            name='summary',
            field=models.TextField(default='HEllo', max_length=200),
        ),
    ]
