# Generated by Django 5.0.1 on 2024-02-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_personalcv_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcv',
            name='summary',
            field=models.TextField(default='HEllo', max_length=3000),
        ),
    ]
